// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.34
// source: scheduler.proto

package pb

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_scheduler_proto struct{}

func (drpcEncoding_File_scheduler_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_scheduler_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_scheduler_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_scheduler_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_scheduler_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCSchedulerServerClient interface {
	DRPCConn() drpc.Conn

	Register(ctx context.Context, in *Task) (*Empty, error)
}

type drpcSchedulerServerClient struct {
	cc drpc.Conn
}

func NewDRPCSchedulerServerClient(cc drpc.Conn) DRPCSchedulerServerClient {
	return &drpcSchedulerServerClient{cc}
}

func (c *drpcSchedulerServerClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcSchedulerServerClient) Register(ctx context.Context, in *Task) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/scheduler.SchedulerServer/Register", drpcEncoding_File_scheduler_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCSchedulerServerServer interface {
	Register(context.Context, *Task) (*Empty, error)
}

type DRPCSchedulerServerUnimplementedServer struct{}

func (s *DRPCSchedulerServerUnimplementedServer) Register(context.Context, *Task) (*Empty, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCSchedulerServerDescription struct{}

func (DRPCSchedulerServerDescription) NumMethods() int { return 1 }

func (DRPCSchedulerServerDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/scheduler.SchedulerServer/Register", drpcEncoding_File_scheduler_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCSchedulerServerServer).
					Register(
						ctx,
						in1.(*Task),
					)
			}, DRPCSchedulerServerServer.Register, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterSchedulerServer(mux drpc.Mux, impl DRPCSchedulerServerServer) error {
	return mux.Register(impl, DRPCSchedulerServerDescription{})
}

type DRPCSchedulerServer_RegisterStream interface {
	drpc.Stream
	SendAndClose(*Empty) error
}

type drpcSchedulerServer_RegisterStream struct {
	drpc.Stream
}

func (x *drpcSchedulerServer_RegisterStream) SendAndClose(m *Empty) error {
	if err := x.MsgSend(m, drpcEncoding_File_scheduler_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
